[package]
authors = ["@colinnielsen"]
compiler_version = ">=0.19.0"
name = "ecrecover"
notes = "AMDG"
type = "lib"

[dependencies]
array_helpers = { tag = "v0.30.0", git = "https://github.com/signorecello/noir-array-helpers" }
