[package]
name = "main"
type = "bin"
authors = ["slokh"]
compiler_version = ">=0.38.0"
version = "0.1.0"

[dependencies]
merkle_tree = { path = "../merkle-trees" }
ecrecover = { path = "../ecrecover-noir" }